#cloud-config
users:
  - default
  - name: galtsev001
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      -  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEr/2nFErf65VWkFIihtR0EXBZWIUSf7p3NsTAtnHEkKR8pZOIiepE4K7ockBhF1mb7UNJkh5LfCNn9VxSSvHZo6/zkwRiWcIfKf2trGwrKI8AX/eiGuledQ4znX/CjL6f8GrTcq4Tb0eplz7E5+5Nyty6k0z08Hq7Yf9JIm34aXOsbqd9ESiPl1Xua1lVQXZ8KBOguwwnWIUGWEcmStAh8SC0uSsCmk8SB8D33ik86w8eEEMsvAcTX7dxcRZ3jpdRe+BCpdeIHEjUmiMTUNoJj9NZTNK3vm9igxAzWemxbx0GwIIdNOc0A90UmnPp8VjuS27smKkadQmrhnA12Njo8ZQvnxGIMchzfN3WftVzfE/AYet1Cbrvb1G5fw5+41uNqGsBhYn1jS4PqoVj9Mw40i1EM4Ifg8NoMFsn55ribfTb4q7J7Febapi3wHXngF62OgfChnTQIG8XoSAyNXOrBKW7qU6q+HzzNQh5UHUXz/vZTpKSiM4QL5/ZawLNj3c= galtsev001@galtsev001-K54HR